### ISSUE TITLE
Unable to run jDeodorant on Jgroups-2.10.0 System

### ISSUE THREAD

**Issue by sergiotp** [tsantalis/JDeodorant#4]
Hi,

I'm trying to run jDeodorant (feature envy) on [jgroups-2.10.0.zip](https://github.com/tsantalis/JDeodorant/files/198412/jgroups-2.10.0.zip) but i'm getting StackOverFlow errors. The error occurs in Linux and MacOs.

If anyone knows what is going on or have any idea about what is causing the problem, please help.

Thank you!

**Comment by tsantalis** [comment]
Thank you for reporting this issue.
This was an infinite recursion bug occurring when the delegate method is the same as the delegator method.

Such a case is method
org.jgroups.stack.Protocol.down(org.jgroups.Event):java.lang.Object
where method down() delegates to itself through field down_prot (Protocol self-reference)

```
public Object down(Event evt) {
    return down_prot.down(evt);
}
```

The bug was fixed and a new version will be released soon.

**Comment by sergiotp** [comment]
Thank you!

**Comment by tsantalis** [comment]
New release 5.0.56 just came out!
You can update through Eclipse Marketplace client or by simply checking for updates.
