### ISSUE TITLE
Template generics and final keyword problem in Long Method Extraction

### ISSUE THREAD

**Issue by feroozkhanchintu** [tsantalis/JDeodorant#56]
Project : crawler4j (https://github.com/yasserg/crawler4j)
package : edu.uci.ics.crawler4j.crawler
Class name : CrawlController
method name : start 
variable criterion : monitorThread

When I refactor this method, the generics from the original method is not added to the refactored method and the final keyword to the parameters is added in the extracted method.

Original method signature : `protected <T extends WebCrawler> void start(final WebCrawlerFactory<T> crawlerFactory, final int numberOfCrawlers, boolean isBlocking)`

After refactoring : `private Thread monitorThread(CrawlController.WebCrawlerFactory<T> crawlerFactory, List<Thread> threads, List<T> crawlers) throws java.lang.Exception, com.sleepycat.je.DatabaseException`

**Comment by tsantalis** [comment]
The bug has been replicated.
Type parameter `<T extends WebCrawler>` needs to be added in the extracted method signature.
All parameters of the extracted method should be declared `final`.

Statement `final CrawlController controller = this;`
should not be duplicated in the original method,
because it is accessed only within the statement using an anonymous class as initializer
`Thread monitorThread = new Thread(new Runnable() {...});`
which is eventually extracted.
