### ISSUE TITLE
Help wanted. Run JDeodorant without having eclipse installed

### ISSUE THREAD

**Issue by adrianiriciuc** [tsantalis/JDeodorant#60]
Hello,

I followed [this](https://users.encs.concordia.ca/~nikolaos/jdeodorant/index.php?option=com_content&view=article&id=87:how-can-i-execute-jdeodorant-in-headless-mode&catid=27:installation-questions&Itemid=41) article and i managed to run JDeodorant from command line. However it would be better for me to run this without using eclipse at all. Is this possible?

It wouldn't be an issue if it needs to create some extra files if it can do this automatically, the only concern is to not have eclipse installed.

**Comment by dmazinanian** [comment]
Hi,

It is possible to make an Eclipse product for your target platform (Windows, Mac, Linux) that runs JDeodorant in the command line.

The application that you are downloading from [here](https://users.encs.concordia.ca/~nikolaos/jdeodorant/index.php?option=com_content&view=article&id=87:how-can-i-execute-jdeodorant-in-headless-mode&catid=27:installation-questions&Itemid=41) only prints the refactoring opportunities, as detected by JDeodorant. We have another application [here](https://github.com/tsantalis/jdeodorant-commandline) that also _applies_ refactorings (for now only for duplicated code, Dr. Tsantalis has been working on the God Class instances as well, though it is still experimental). For this application, we have provided the necessary configuration so that you can export an Eclipse product that runs from the command line. You won't need to install anything on your target machine (Except Java): you'll export the application from Eclipse once, and then move the entire generated package to your target machine, and run the executable in the command line. You can find the necessary steps [here](https://github.com/tsantalis/jdeodorant-commandline#running-as-a-standalone-command-line-application).

Unfortunately, we don't have the product configuration files for the application that you are downloading. On the other hand, the other application for which we have the product configuration does not print the opportunities. There are different options:

1. You try and take the necessary steps for exporting an Eclipse product from the application that you are downloading ([this](http://www.vogella.com/tutorials/EclipseProductDeployment/article.html) could be a starting point).

2. You make some changes to the code of the application that has eclipse configuration so that it prints the opportunities (compare Application.java files in the source code of the two applications). Then export the Eclipse application.

3. You bear with us for some time, we will either try to add the product configurations to the first application, or we will add the code for printing all opportunities to the second one (hopefully soon).

Hope this helps for now.

**Comment by dmazinanian** [comment]
OK, I added the support for printing the identified refactoring opportunities to console to _jdeodorant-commandline_ project. This is experimental though, I tested it and it seems to be working on Mac. You will need to follow the steps mentioned [here](https://github.com/tsantalis/jdeodorant-commandline#running-as-a-standalone-command-line-application). However, in step 1, instead of cloning (or downloading) jdeodorant-commandline project, get the project from [this branch](https://github.com/tsantalis/jdeodorant-commandline/tree/print-opportunities). The code is not yet in the master branch, we will do some more tests and then we might merge it with the master branch later. The rest of the steps are the same, and it should normally work.

After exporting the product, you will need to run it like this:

`./eclipse -m print_opportunities -pd path/to/.project`

Note that, the `path/to/.project` is the path to the `.project` file (normally in the project folder that you need to analyze).

As you can see here, I'm running it with no problem: 

![image](https://cloud.githubusercontent.com/assets/3718458/23323698/c17b5eec-fab7-11e6-971d-0c7f0b094372.png)

Hope this helps. Please let us know should you encounter any problem.

**Comment by adrianiriciuc** [comment]
Ok, thanks for the help.

I will need to get some time to spend on this, but thank you for the support
