### ISSUE TITLE
Using Multiple Smell Scans leads to "Incomprehensible Rainbow" Documents 🌈

### ISSUE THREAD

**Issue by starlocke** [tsantalis/JDeodorant#82]
(details to come later)

**Comment by tsantalis** [comment]
I am very curious for this one!

**Comment by starlocke** [comment]
Okay. So, originally, I thought it was a symptom of "multiple smell scanners from JDeodorant", but it's actually a UX oversight when JDeodorant is used in combination with Code Coverage testing/reporting.

- Take _that small project from yesterday_.
- Within Eclipse, having JDeodorant also installed, load the project.
- Run "Bad Smells -> Long Method" for all of "src".
- Explore the first smell in the "Long Method" tab/view.
- Then do the "Run Coverage as JUnit" operation on "tests" (right-clicked on "tests" to start this).
- Go back to the "Long Method" tab/view.
- Try exploring the first smell. Try exploring the second smell.

Expected result:

- The "Long Method" smells would visually stand out from the regular code.
- That may mean suppressing all other highlights, like the ones that come from Code Coverage; which could mean wiping them out, or softening/muting their colours.
- That may also mean using different colours.
- That may also be supported by text or symbol annotations, like "virtual" comments on the right-side of every affected line.
- There may be other UI/UX options available.

Actual result:

- The "Long Method" smells are completely lost in the "Code Coverage" highlights, and indistinguishable, visually speaking.
- Also, repeatedly "double-clicking" on a listed "long method" case might toggle on/off some highlighting for particular lines (probably somewhat randomly in a race-condition).

Screenshot 1 of 2 (many pointers in one):

![000140](https://user-images.githubusercontent.com/1019999/97013248-da3fa500-1516-11eb-8b5c-ec3ebdf7a322.png)

Screenshot 2 of 2 (pointing out that one line whose highlight colour randomly flips):

![000141](https://user-images.githubusercontent.com/1019999/97013344-f2afbf80-1516-11eb-810e-f86bccda7004.png)

**Comment by tsantalis** [comment]
Thanks @starlocke That's because both JDeodorant and Eclipse Code coverage tool are using the same marker annotation mechanism to highlight the code.

If you go to the `Coverage` window and click on `Remove Active Session` the test coverage highlights will disappear.

![Screenshot from 2020-10-24 13-49-49](https://user-images.githubusercontent.com/1483516/97088607-02ef9980-1600-11eb-8d8d-e595c2cd3dc5.png)

JDeodorant clears all its previously placed marker annotations, whenever you double-click on another refactoring opportunity.
